#!/usr/bin/env bash
# Dummy replacement for the docker command

# Exit when any command fails
set -e
echo "***** dummy docker script starting sub-build in $PWD"

echo "cd $PWD"
cd "$PWD"
echo "export VERBOSE=1"
export VERBOSE=1
echo "python build.py"
python build.py

echo "***** dummy docker script finished sub-build in $PWD"
