#!/usr/bin/env bash
# Dummy replacement for the docker command

echo "***** Paused in dummy docker script. Open another window and enter:"

echo "cd $PWD"
echo "export VERBOSE=1"
echo "python build.py"

echo "***** Press Enter to continue build..."
read docker_tmp
