#!/usr/bin/env bash
# Dummy replacement for the docker command

# Exit when any command fails
set -e
echo "***** dummy docker script starting sub-build in $PWD"

# Turn on echo
set -x
echo "sed 's/pool console/pool NOTUSED_console/g' build.ninja"

# For verbose cmake build, export VERBOSE=1
export VERBOSE=

# Build the library
python build.py

# Turn off echo
set +x
echo "***** dummy docker script finished sub-build in $PWD"
